import Head from "next/head";
import Main from "../components/Main";
import MenuNav from "../components/MenuNav";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import { GetStaticProps } from "next";
import { collection, getDocs } from "firebase/firestore";

import { db } from "../services/firebase";

export interface IProjects {
  title: string;
  description: string;
  image: string;
  link: string;
  gitLink: string;
}

interface IHome {
  arrayProjects: string;
}

export default function Home({ arrayProjects }: IHome) {
  const projects = JSON.parse(arrayProjects);

  return (
    <div className="bg-primary-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuNav />

      <section>
        <Main />
      </section>

      <section>
        <About />
      </section>

      <section>
        <Projects projects={projects} />
      </section>

      <section>
        <Contact />
      </section>

      <section>
        <Footer />
      </section>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const projects: IProjects[] = [];

  const response = await getDocs(collection(db, "projects"));
  response.forEach((project) => {
    projects.push(project.data() as IProjects);
  });

  const arrayProjects = JSON.stringify(projects);

  return {
    props: { arrayProjects },
  };
};
