import Head from "next/head";
import Main from "../components/Main";
import MenuNav from "../components/MenuNav";
import About from "../components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuNav />

      <section>
        <Main />
      </section>
      <section>
        <About />
      </section>
    </div>
  );
}
